### ISSUE TITLE
case 1084324

### ISSUE THREAD

**Issue by spalmertwilio** [TwilioDevEd/server-notifications-node#11]
npm test

> server-notifications-node@1.0.0 test /home/ubuntu/workspace/twilio-server/server-notifications-node 
> NODE_ENV=test node_modules/.bin/mocha test

Twilio notifications on error 
GET /error 
An application error has occurred: 
Error: Derp. An error occurred. 
at /home/ubuntu/workspace/twilio-server/server-notifications-node/controllers/router.js:4:11 
at Layer.handle [as handle_request] (/home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/express/lib/router/layer.js:95:5) 
at next (/home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/express/lib/router/route.js:137:13) 
at Route.dispatch (/home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/express/lib/router/route.js:112:3) 
at Layer.handle [as handle_request] (/home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/express/lib/router/layer.js:95:5) 
at /home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/express/lib/router/index.js:281:22 
at Function.process_params (/home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/express/lib/router/index.js:335:12) 
at next (/home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/express/lib/router/index.js:275:10) 
at Function.handle (/home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/express/lib/router/index.js:174:3) 
at router (/home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/express/lib/router/index.js:47:12) 
at Layer.handle [as handle_request] (/home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/express/lib/router/layer.js:95:5) 
at trim_prefix (/home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/express/lib/router/index.js:317:13) 
at /home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/express/lib/router/index.js:284:7 
at Function.process_params (/home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/express/lib/router/index.js:335:12) 
at next (/home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/express/lib/router/index.js:275:10) 
at /home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/connect-flash/lib/flash.js:21:5 
at Layer.handle [as handle_request] (/home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/express/lib/router/layer.js:95:5) 
at trim_prefix (/home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/express/lib/router/index.js:317:13) 
at /home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/express/lib/router/index.js:284:7 
at Function.process_params (/home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/express/lib/router/index.js:335:12) 
at next (/home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/express/lib/router/index.js:275:10) 
at session (/home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/express-session/index.js:454:7) 
at Layer.handle [as handle_request] (/home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/express/lib/router/layer.js:95:5) 
at trim_prefix (/home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/express/lib/router/index.js:317:13) 
at /home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/express/lib/router/index.js:284:7 
at Function.process_params (/home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/express/lib/router/index.js:335:12) 
at next (/home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/express/lib/router/index.js:275:10) 
at urlencodedParser (/home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/body-parser/lib/types/urlencoded.js:91:7) 
at Layer.handle [as handle_request] (/home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/express/lib/router/layer.js:95:5) 
at trim_prefix (/home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/express/lib/router/index.js:317:13) 
at /home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/express/lib/router/index.js:284:7 
at Function.process_params (/home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/express/lib/router/index.js:335:12) 
at next (/home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/express/lib/router/index.js:275:10) 
at SendStream.error (/home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/serve-static/index.js:121:7) 
at emitOne (events.js:96:13) 
at SendStream.emit (events.js:188:7) 
at SendStream.error (/home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/send/index.js:282:17) 
at SendStream.onStatError (/home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/send/index.js:433:12) 
at next (/home/ubuntu/workspace/twilio-server/server-notifications-node/node_modules/send/index.js:743:16) 
at FSReqWrap.oncomplete (fs.js:123:15) 
Administrator notified 
Administrator notified 
✓ should return an error (54ms)

twilioClient 
Administrator notified 
✓ should send sms message and return promise with result

2 passing (76ms)

**Comment by joliveros** [comment]
@spalmertwilio it looks like the purpose of this sample application is to throw this error and send a notification via sms. Which looks like is the case. I would ignore the stacktrace.
